#!/usr/bin/env python3
"""
Get the latest transform from "guess_frame_id" to "frame_id" and call the "/rtabmap/reset_odometry_to_pose" service
"""

import math

import rclpy
import tf2_ros
import tf2_msgs
from rclpy.node import Node

from mbari_rtabmap_msgs.srv import ResetPose


def get_euler_ypr(x: float, y: float, z: float, w: float) -> (float, float, float):
    """
    Get the yaw, pitch, roll from a quaternion.
    Ported from tf2/include/tf2/impl/utils.h.
    
    Args:
        x: x component of the quaternion
        y: y component of the quaternion
        z: z component of the quaternion
        w: w component of the quaternion
    
    Returns:
        yaw: yaw in radians
        pitch: pitch in radians
        roll: roll in radians
    """
    sqx = x * x
    sqy = y * y
    sqz = z * z
    sqw = w * w

    sarg = -2 * (x * z - w * y) / (sqx + sqy + sqz + sqw)

    if sarg <= -0.99999:
        pitch = -0.5 * math.pi
        roll = 0
        yaw = -2 * math.atan2(y, x)
    elif sarg >= 0.99999:
        pitch = 0.5 * math.pi
        roll = 0
        yaw = 2 * math.atan2(y, x)
    else:
        pitch = math.asin(sarg)
        roll = math.atan2(2 * (y * z + w * x), sqw - sqx - sqy + sqz)
        yaw = math.atan2(2 * (x * y + w * z), sqw + sqx - sqy - sqz)
    
    return yaw, pitch, roll


class ResetOdometryNode(Node):
    """
    Reset Odometry Node
    """
    
    def __init__(self):
        super().__init__('reset_odometry')
        self._declare_parameters()
        
        # Get parameters
        self.guess_frame_id = self.get_parameter('guess_frame_id').value
        self.frame_id = self.get_parameter('frame_id').value
        
        # Create the tf subscriber
        self.create_subscription(
            tf2_msgs.msg.TFMessage,
            '/tf',
            self.tf_callback,
            1
        )
        
        # Create the service client
        self.service_name = '/rtabmap/reset_odom_to_pose'
        self.client = self.create_client(ResetPose, self.service_name)
        
        # Wait for the service to become available
        timeout_sec = 1.0
        while not self.client.wait_for_service(timeout_sec=timeout_sec):
            self.get_logger().info(f'Service {self.service_name} not available, waiting for {timeout_sec} s...')
        self.get_logger().info(f'Service {self.service_name} available')
        
        # Create the request
        self.req = ResetPose.Request()
    
    def _declare_parameters(self):
        """
        Declare all node parameters.
        """
        self.declare_parameter('guess_frame_id', rclpy.Parameter.Type.STRING)
        self.declare_parameter('frame_id', rclpy.Parameter.Type.STRING)
    
    def tf_callback(self, msg):
        """
        Callback for the tf subscriber.
        
        Args:
            msg: tf message
        """
        # Get the latest transform
        t = msg.transforms[-1]
        if t.child_frame_id == self.frame_id and t.header.frame_id == self.guess_frame_id:
            # Reset odometry
            self.reset_odometry(t)
            self.get_logger().info(f'Reset odometry')
            self.destroy_node()
            raise SystemExit(0)
        
    def reset_odometry(self, t):
        # Construct the request
        self.req.x = t.transform.translation.x
        self.req.y = t.transform.translation.y
        self.req.z = t.transform.translation.z
        
        # Convert the quaternion to yaw, pitch, roll
        yaw, pitch, roll = get_euler_ypr(
            t.transform.rotation.x,
            t.transform.rotation.y,
            t.transform.rotation.z,
            t.transform.rotation.w
        )
        self.req.roll = roll
        self.req.pitch = pitch
        self.req.yaw = yaw
        
        # Call the service
        self.future = self.client.call_async(self.req)


def main(args=None):
    rclpy.init(args=args)
    
    node = ResetOdometryNode()

    try:
        rclpy.spin(node)
    except SystemExit:
        pass
    
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
