#!/usr/bin/env python3

import numpy as np
import rclpy
import signal
import tf2_ros
from geometry_msgs.msg import PoseWithCovarianceStamped
from rclpy.node import Node
from rclpy.qos import QoSHistoryPolicy, QoSProfile, QoSReliabilityPolicy
from scipy.spatial.transform import Rotation as R


class SubPub(Node):

    def __init__(self):
        super().__init__('depth_subscriber')

        # Declare parameters
        self._declare_parameters()

        # Get parameters
        self.depth_subscriber = self.get_parameter('depth_subscriber').value
        self.depth_publisher = self.get_parameter('depth_publisher').value
        self.depth_ned_frame_id = self.get_parameter('depth_ned_frame_id').value
        self.base_link_frame_id = self.get_parameter('base_link_frame_id').value

        # Initialize transform matrices
        self.transform = None

        # Create a subscriber for the depth
        self.depth_subscriber = self.create_subscription(
            PoseWithCovarianceStamped,
            self.depth_subscriber,
            self.depth_callback,
            QoSProfile(reliability=QoSReliabilityPolicy.BEST_EFFORT,
                       history=QoSHistoryPolicy.KEEP_LAST,
                       depth=1)
        )

        # Create a publisher for the transformed depth
        self.depth_publisher = self.create_publisher(
            PoseWithCovarianceStamped,
            self.depth_publisher,
            QoSProfile(depth=1))

        # Create tf buffer and listener
        self._tf_buffer = tf2_ros.buffer.Buffer()
        self._tf_listener = tf2_ros.transform_listener.TransformListener(self._tf_buffer, self)

        # Register signal handler for SIGINT
        signal.signal(signal.SIGINT, self.signal_handler)

    def _declare_parameters(self):
        """
        Declare parameters for the node
        """
        self.declare_parameter('depth_subscriber', rclpy.Parameter.Type.STRING)
        self.declare_parameter('depth_publisher', rclpy.Parameter.Type.STRING)
        self.declare_parameter('depth_ned_frame_id', rclpy.Parameter.Type.STRING)
        self.declare_parameter('base_link_frame_id', rclpy.Parameter.Type.STRING)

    def depth_callback(self, msg) -> None:
        """
        Callback function for the depth subscriber
        """
        # Process the received depth
        self.depth_transform = np.eye(4)
        self.depth_transform[2, -1] = msg.pose.pose.position.z
        self.depth_covariance = msg.pose.covariance
        self.depth_stamp = msg.header.stamp

        # Lookup transform from base_link to depth_link
        if self.transform is None:
            try:
                t = self._tf_buffer.lookup_transform(self.base_link_frame_id,
                                                     self.depth_ned_frame_id,
                                                     self.depth_stamp).transform
                rotation = R.from_quat([t.rotation.x, t.rotation.y, t.rotation.z, t.rotation.w])
                self.transform = np.eye(4)
                self.transform[:3, :3] = rotation.as_matrix()
                self.transform[:3, -1] = np.array([t.translation.x, t.translation.y, t.translation.z])
                self.transform = np.linalg.inv(self.transform)

            except tf2_ros.TransformException as ex:
                self.get_logger().info(f'Could not transform depth to base_link: {ex}')

        else:
            # Transform depth from depth_base_link_abs_frd to base_link
            self.depth_frd = (self.transform @ self.depth_transform)[2, -1]

            # Publish transformed message
            self.depth_publish()

    def depth_publish(self) -> None:
        """
        Publish the transformed depth
        """
        # Create depth message
        depth_msg = PoseWithCovarianceStamped()

        # Populate depth message
        depth_msg.header.frame_id = self.base_link_frame_id
        depth_msg.header.stamp = self.depth_stamp
        depth_msg.pose.pose.position.z = self.depth_frd
        depth_msg.pose.covariance = self.depth_covariance

        # Publish message
        self.depth_publisher.publish(depth_msg)

    def signal_handler(self, sig, frame) -> None:
        """
        Signal handler for SIGINT
        """
        self.get_logger().info('Shutting down depth_filter node...')
        self.destroy_node()
        rclpy.shutdown()


def main(args=None):
    rclpy.init(args=args)

    depth_subscriber = SubPub()

    rclpy.spin(depth_subscriber)


if __name__ == '__main__':
    main()
