#!/usr/bin/env python3

from dataclasses import dataclass
from typing import List

import numpy as np
import rclpy
import tf2_msgs.msg
from geometry_msgs.msg import PoseWithCovarianceStamped
from rclpy.node import Node
from rclpy.qos import QoSHistoryPolicy, QoSProfile, QoSReliabilityPolicy
from scipy.spatial.transform import Rotation as R


class SubPub(Node):

    def __init__(self):
        super().__init__('depth_subscriber')

        # Declare parameters
        self._declare_parameters()

        # Get parameters
        self.depth_subscriber = self.get_parameter('depth_subscriber').value
        self.depth_publisher = self.get_parameter('depth_publisher').value
        self.depth_ned_frame_id = self.get_parameter('depth_ned_frame_id').value
        self.depth_frd_frame_id = self.get_parameter('depth_frd_frame_id').value
        self.base_link_frame_id = self.get_parameter('base_link_frame_id').value
        
        # Initialize transform matrices
        self.static_transforms = dict()
        self.transform = None

        # Create a subscriber for the static transform
        self.static_transform_subscriber = self.create_subscription(
            tf2_msgs.msg.TFMessage,
            '/tf_static',
            self.static_transform_callback,
            QoSProfile(depth=10)
        )

        # Create a subscriber for the depth
        self.depth_subscriber = self.create_subscription(
            PoseWithCovarianceStamped,
            self.depth_subscriber,
            self.depth_callback,
            QoSProfile(reliability=QoSReliabilityPolicy.BEST_EFFORT,
                       history=QoSHistoryPolicy.KEEP_LAST,
                       depth=10)
        )

        # Create a publisher for the transformed depth
        self.depth_publisher = self.create_publisher(
            PoseWithCovarianceStamped,
            self.depth_publisher,
            QoSProfile(depth=10))

    def _declare_parameters(self):
        """
        Declare parameters for the node
        """
        self.declare_parameter('depth_subscriber', rclpy.Parameter.Type.STRING)
        self.declare_parameter('depth_publisher', rclpy.Parameter.Type.STRING)
        self.declare_parameter('depth_ned_frame_id', rclpy.Parameter.Type.STRING)
        self.declare_parameter('depth_frd_frame_id', rclpy.Parameter.Type.STRING)
        self.declare_parameter('base_link_frame_id', rclpy.Parameter.Type.STRING)

    def static_transform_callback(self, msg) -> None:
        """
        Callback function for the static transform subscriber
        """
        # Process the received static transform
        for transform_stamped in msg.transforms:

            # If the transform is not in the dictionary, add it
            if transform_stamped.header.frame_id not in self.static_transforms.keys():
                self.static_transforms[transform_stamped.header.frame_id] = dict()

            # Parse rotation and translation components
            translation = transform_stamped.transform.translation
            rotation = transform_stamped.transform.rotation
            x, y, z = translation.x, translation.y, translation.z
            qx, qy, qz, qw = rotation.x, rotation.y, rotation.z, rotation.w
            transform = TransformMatrix(x, y, z, qx, qy, qz, qw)

            # Create transformation matrix from TransformMatrix class
            self.static_transforms[transform_stamped.header.frame_id][transform_stamped.child_frame_id] = transform

        if self.depth_frd_frame_id in self.static_transforms:
            if self.depth_ned_frame_id in self.static_transforms[self.depth_frd_frame_id]:
                self.transform = self.static_transforms[self.depth_frd_frame_id][self.depth_ned_frame_id].transformation

    def depth_callback(self, msg) -> None:
        """
        Callback function for the depth subscriber
        """
        # Process the received depth
        self.depthTransform = TransformMatrix(0.0, 0.0, msg.pose.pose.position.z, 0.0, 0.0, 0.0, 1.0)
        self.depth_covariance = msg.pose.covariance
        self.depth_stamp = msg.header.stamp

        if self.transform is not None:
            # Transform depth from depth_base_link_abs_frd to base_link
            self.depth_frd = (self.transform @ self.depthTransform.transformation)[2, -1]

            # Publish transformed message
            self.depth_publish()

    def depth_publish(self) -> None:
        """
        Publish the transformed depth
        """
        # Create depth message
        depth_msg = PoseWithCovarianceStamped()

        # Populate depth message
        depth_msg.header.frame_id = self.base_link_frame_id
        depth_msg.header.stamp = self.depth_stamp
        depth_msg.pose.pose.position.z = self.depth_frd
        depth_msg.pose.covariance = self.depth_covariance

        # Publish message
        self.depth_publisher.publish(depth_msg)
        print("Depth: ", self.depth_frd)


@dataclass
class vector:
    """
    Vector structure

    x: float
        x component.
    y: float
        y component.
    z: float
        z component.
    """
    x: float
    y: float
    z: float

    def vector(self) -> np.ndarray:
        return np.array([self.x, self.y, self.z])


@dataclass
class quaternion:
    """
    Quaternion structure

    x: float
        x component.
    y: float
        y component.
    z: float
        z component.
    w: float
        w component.
    """
    x: float
    y: float
    z: float
    w: float

    def rph(self) -> np.ndarray:
        return R.from_quat([self.x, self.y, self.z, self.w]).as_euler("ZYX").flatten()[::-1]

    def rot_mat(self) -> np.ndarray:
        return R.from_quat([self.x, self.y, self.z, self.w]).as_matrix()

    def quaternion(self) -> np.ndarray:
        return np.array([self.x, self.y, self.z, self.w])


class TransformMatrix:

    def __init__(self, x: float, y: float, z: float, qx: float, qy: float, qz: float, qw: float) -> None:
        self.translation = [x, y, z]
        self.rotation = [qx, qy, qz, qw]

    @property
    def transformation(self) -> np.ndarray:
        """Transformation matrix"""
        t = np.eye(4)
        t[:3, :3] = self._rotation.rot_mat()
        t[:3, -1] = self._translation.vector()
        return t

    @property
    def translation(self) -> vector:
        """Translation component of transformation matrix"""
        return self._translation

    @translation.setter
    def translation(self, value: List[float]) -> None:
        self._translation = vector(value[0], value[1], value[2])

    @property
    def rotation(self) -> quaternion:
        """Translation component of transformation matrix"""
        return self._rotation

    @rotation.setter
    def rotation(self, value: List[float]) -> None:
        self._rotation = quaternion(value[0], value[1], value[2], value[3])


def main(args=None):
    rclpy.init(args=args)

    depth_subscriber = SubPub()

    rclpy.spin(depth_subscriber)

    depth_subscriber.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
